name = "reST"
uuid = "56e5230c-73bd-11e9-145f-29838fa039cf"
authors = ["Apua Juan <apuaj@hpe.com>"]
version = "0.1.0"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PyCall", "Printf"]
